//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegracionSI_BD_Empresa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas
    {
        public int EmpresaID { get; set; }
        public string RazonSocial { get; set; }
        public int Ruc { get; set; }
    }
}
