//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AppOrdenesCompra.RefArticulos {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SWArticulosSoap", Namespace="http://tempuri.org/")]
    public partial class SWArticulos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SeleccionarAritculosOperationCompleted;
        
        private System.Threading.SendOrPostCallback SeleccionarArticuloPorIDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SWArticulos() {
            this.Url = global::AppOrdenesCompra.Properties.Settings.Default.AppOrdenesCompra_RefArticulos_SWArticulos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SeleccionarAritculosCompletedEventHandler SeleccionarAritculosCompleted;
        
        /// <remarks/>
        public event SeleccionarArticuloPorIDCompletedEventHandler SeleccionarArticuloPorIDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeleccionarAritculos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Articulos[] SeleccionarAritculos() {
            object[] results = this.Invoke("SeleccionarAritculos", new object[0]);
            return ((Articulos[])(results[0]));
        }
        
        /// <remarks/>
        public void SeleccionarAritculosAsync() {
            this.SeleccionarAritculosAsync(null);
        }
        
        /// <remarks/>
        public void SeleccionarAritculosAsync(object userState) {
            if ((this.SeleccionarAritculosOperationCompleted == null)) {
                this.SeleccionarAritculosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeleccionarAritculosOperationCompleted);
            }
            this.InvokeAsync("SeleccionarAritculos", new object[0], this.SeleccionarAritculosOperationCompleted, userState);
        }
        
        private void OnSeleccionarAritculosOperationCompleted(object arg) {
            if ((this.SeleccionarAritculosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeleccionarAritculosCompleted(this, new SeleccionarAritculosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeleccionarArticuloPorID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Articulos SeleccionarArticuloPorID(string ID) {
            object[] results = this.Invoke("SeleccionarArticuloPorID", new object[] {
                        ID});
            return ((Articulos)(results[0]));
        }
        
        /// <remarks/>
        public void SeleccionarArticuloPorIDAsync(string ID) {
            this.SeleccionarArticuloPorIDAsync(ID, null);
        }
        
        /// <remarks/>
        public void SeleccionarArticuloPorIDAsync(string ID, object userState) {
            if ((this.SeleccionarArticuloPorIDOperationCompleted == null)) {
                this.SeleccionarArticuloPorIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeleccionarArticuloPorIDOperationCompleted);
            }
            this.InvokeAsync("SeleccionarArticuloPorID", new object[] {
                        ID}, this.SeleccionarArticuloPorIDOperationCompleted, userState);
        }
        
        private void OnSeleccionarArticuloPorIDOperationCompleted(object arg) {
            if ((this.SeleccionarArticuloPorIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeleccionarArticuloPorIDCompleted(this, new SeleccionarArticuloPorIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Articulos {
        
        private string artIDField;
        
        private string artDescripField;
        
        /// <remarks/>
        public string ArtID {
            get {
                return this.artIDField;
            }
            set {
                this.artIDField = value;
            }
        }
        
        /// <remarks/>
        public string ArtDescrip {
            get {
                return this.artDescripField;
            }
            set {
                this.artDescripField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SeleccionarAritculosCompletedEventHandler(object sender, SeleccionarAritculosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeleccionarAritculosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeleccionarAritculosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Articulos[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Articulos[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SeleccionarArticuloPorIDCompletedEventHandler(object sender, SeleccionarArticuloPorIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeleccionarArticuloPorIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeleccionarArticuloPorIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Articulos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Articulos)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591