//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Chev_Front.SW_Chev {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SW_ChevSoap", Namespace="http://tempuri.org/")]
    public partial class SW_Chev : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SeleccionarAutosChevOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarAutoChevOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarAutoChevOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarAutoChevOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SW_Chev() {
            this.Url = global::Chev_Front.Properties.Settings.Default.Chev_Front_SW_Chev_SW_Chev;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SeleccionarAutosChevCompletedEventHandler SeleccionarAutosChevCompleted;
        
        /// <remarks/>
        public event InsertarAutoChevCompletedEventHandler InsertarAutoChevCompleted;
        
        /// <remarks/>
        public event EliminarAutoChevCompletedEventHandler EliminarAutoChevCompleted;
        
        /// <remarks/>
        public event ActualizarAutoChevCompletedEventHandler ActualizarAutoChevCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeleccionarAutosChev", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Auto_CHEV[] SeleccionarAutosChev() {
            object[] results = this.Invoke("SeleccionarAutosChev", new object[0]);
            return ((Auto_CHEV[])(results[0]));
        }
        
        /// <remarks/>
        public void SeleccionarAutosChevAsync() {
            this.SeleccionarAutosChevAsync(null);
        }
        
        /// <remarks/>
        public void SeleccionarAutosChevAsync(object userState) {
            if ((this.SeleccionarAutosChevOperationCompleted == null)) {
                this.SeleccionarAutosChevOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeleccionarAutosChevOperationCompleted);
            }
            this.InvokeAsync("SeleccionarAutosChev", new object[0], this.SeleccionarAutosChevOperationCompleted, userState);
        }
        
        private void OnSeleccionarAutosChevOperationCompleted(object arg) {
            if ((this.SeleccionarAutosChevCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeleccionarAutosChevCompleted(this, new SeleccionarAutosChevCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertarAutoChev", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertarAutoChev(Auto_CHEV chev) {
            this.Invoke("InsertarAutoChev", new object[] {
                        chev});
        }
        
        /// <remarks/>
        public void InsertarAutoChevAsync(Auto_CHEV chev) {
            this.InsertarAutoChevAsync(chev, null);
        }
        
        /// <remarks/>
        public void InsertarAutoChevAsync(Auto_CHEV chev, object userState) {
            if ((this.InsertarAutoChevOperationCompleted == null)) {
                this.InsertarAutoChevOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarAutoChevOperationCompleted);
            }
            this.InvokeAsync("InsertarAutoChev", new object[] {
                        chev}, this.InsertarAutoChevOperationCompleted, userState);
        }
        
        private void OnInsertarAutoChevOperationCompleted(object arg) {
            if ((this.InsertarAutoChevCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarAutoChevCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarAutoChev", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarAutoChev(Auto_CHEV chev) {
            object[] results = this.Invoke("EliminarAutoChev", new object[] {
                        chev});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarAutoChevAsync(Auto_CHEV chev) {
            this.EliminarAutoChevAsync(chev, null);
        }
        
        /// <remarks/>
        public void EliminarAutoChevAsync(Auto_CHEV chev, object userState) {
            if ((this.EliminarAutoChevOperationCompleted == null)) {
                this.EliminarAutoChevOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarAutoChevOperationCompleted);
            }
            this.InvokeAsync("EliminarAutoChev", new object[] {
                        chev}, this.EliminarAutoChevOperationCompleted, userState);
        }
        
        private void OnEliminarAutoChevOperationCompleted(object arg) {
            if ((this.EliminarAutoChevCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarAutoChevCompleted(this, new EliminarAutoChevCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarAutoChev", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ActualizarAutoChev(Auto_CHEV chev) {
            object[] results = this.Invoke("ActualizarAutoChev", new object[] {
                        chev});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarAutoChevAsync(Auto_CHEV chev) {
            this.ActualizarAutoChevAsync(chev, null);
        }
        
        /// <remarks/>
        public void ActualizarAutoChevAsync(Auto_CHEV chev, object userState) {
            if ((this.ActualizarAutoChevOperationCompleted == null)) {
                this.ActualizarAutoChevOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarAutoChevOperationCompleted);
            }
            this.InvokeAsync("ActualizarAutoChev", new object[] {
                        chev}, this.ActualizarAutoChevOperationCompleted, userState);
        }
        
        private void OnActualizarAutoChevOperationCompleted(object arg) {
            if ((this.ActualizarAutoChevCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarAutoChevCompleted(this, new ActualizarAutoChevCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Auto_CHEV {
        
        private int idField;
        
        private string marca_ChevroletField;
        
        private string modelo_ChevroletField;
        
        private string cilindraje_ChevroletField;
        
        private string anio_ChevroletField;
        
        private string color_ChevroletField;
        
        private string tipo_ChevroletField;
        
        private string con_ChevroletField;
        
        private string fecha_ChevroletField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Marca_Chevrolet {
            get {
                return this.marca_ChevroletField;
            }
            set {
                this.marca_ChevroletField = value;
            }
        }
        
        /// <remarks/>
        public string Modelo_Chevrolet {
            get {
                return this.modelo_ChevroletField;
            }
            set {
                this.modelo_ChevroletField = value;
            }
        }
        
        /// <remarks/>
        public string Cilindraje_Chevrolet {
            get {
                return this.cilindraje_ChevroletField;
            }
            set {
                this.cilindraje_ChevroletField = value;
            }
        }
        
        /// <remarks/>
        public string Anio_Chevrolet {
            get {
                return this.anio_ChevroletField;
            }
            set {
                this.anio_ChevroletField = value;
            }
        }
        
        /// <remarks/>
        public string Color_Chevrolet {
            get {
                return this.color_ChevroletField;
            }
            set {
                this.color_ChevroletField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo_Chevrolet {
            get {
                return this.tipo_ChevroletField;
            }
            set {
                this.tipo_ChevroletField = value;
            }
        }
        
        /// <remarks/>
        public string Con_Chevrolet {
            get {
                return this.con_ChevroletField;
            }
            set {
                this.con_ChevroletField = value;
            }
        }
        
        /// <remarks/>
        public string Fecha_Chevrolet {
            get {
                return this.fecha_ChevroletField;
            }
            set {
                this.fecha_ChevroletField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SeleccionarAutosChevCompletedEventHandler(object sender, SeleccionarAutosChevCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeleccionarAutosChevCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeleccionarAutosChevCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Auto_CHEV[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Auto_CHEV[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void InsertarAutoChevCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EliminarAutoChevCompletedEventHandler(object sender, EliminarAutoChevCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarAutoChevCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarAutoChevCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ActualizarAutoChevCompletedEventHandler(object sender, ActualizarAutoChevCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarAutoChevCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarAutoChevCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591