//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Front_Bus.WebService_AutosEC {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SWAutosECSoap", Namespace="http://tempuri.org/")]
    public partial class SWAutosEC : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SeleccionarAutosChevOperationCompleted;
        
        private System.Threading.SendOrPostCallback SeleccionarAutosEcuadorPorTipoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SWAutosEC() {
            this.Url = global::Front_Bus.Properties.Settings.Default.Front_Bus_WebService_AutosEC_SWAutosEC;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SeleccionarAutosChevCompletedEventHandler SeleccionarAutosChevCompleted;
        
        /// <remarks/>
        public event SeleccionarAutosEcuadorPorTipoCompletedEventHandler SeleccionarAutosEcuadorPorTipoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeleccionarAutosChev", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DTOAutosEcuador[] SeleccionarAutosChev() {
            object[] results = this.Invoke("SeleccionarAutosChev", new object[0]);
            return ((DTOAutosEcuador[])(results[0]));
        }
        
        /// <remarks/>
        public void SeleccionarAutosChevAsync() {
            this.SeleccionarAutosChevAsync(null);
        }
        
        /// <remarks/>
        public void SeleccionarAutosChevAsync(object userState) {
            if ((this.SeleccionarAutosChevOperationCompleted == null)) {
                this.SeleccionarAutosChevOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeleccionarAutosChevOperationCompleted);
            }
            this.InvokeAsync("SeleccionarAutosChev", new object[0], this.SeleccionarAutosChevOperationCompleted, userState);
        }
        
        private void OnSeleccionarAutosChevOperationCompleted(object arg) {
            if ((this.SeleccionarAutosChevCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeleccionarAutosChevCompleted(this, new SeleccionarAutosChevCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeleccionarAutosEcuadorPorTipo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DTOAutosEcuador[] SeleccionarAutosEcuadorPorTipo(string Tipo) {
            object[] results = this.Invoke("SeleccionarAutosEcuadorPorTipo", new object[] {
                        Tipo});
            return ((DTOAutosEcuador[])(results[0]));
        }
        
        /// <remarks/>
        public void SeleccionarAutosEcuadorPorTipoAsync(string Tipo) {
            this.SeleccionarAutosEcuadorPorTipoAsync(Tipo, null);
        }
        
        /// <remarks/>
        public void SeleccionarAutosEcuadorPorTipoAsync(string Tipo, object userState) {
            if ((this.SeleccionarAutosEcuadorPorTipoOperationCompleted == null)) {
                this.SeleccionarAutosEcuadorPorTipoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeleccionarAutosEcuadorPorTipoOperationCompleted);
            }
            this.InvokeAsync("SeleccionarAutosEcuadorPorTipo", new object[] {
                        Tipo}, this.SeleccionarAutosEcuadorPorTipoOperationCompleted, userState);
        }
        
        private void OnSeleccionarAutosEcuadorPorTipoOperationCompleted(object arg) {
            if ((this.SeleccionarAutosEcuadorPorTipoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeleccionarAutosEcuadorPorTipoCompleted(this, new SeleccionarAutosEcuadorPorTipoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DTOAutosEcuador {
        
        private string marca_autosECField;
        
        private string modelo_autosECField;
        
        private string tipo_autosECField;
        
        private string color_autosECField;
        
        private string anio_autosECField;
        
        private string cons_autosECField;
        
        private string img_autosECField;
        
        /// <remarks/>
        public string Marca_autosEC {
            get {
                return this.marca_autosECField;
            }
            set {
                this.marca_autosECField = value;
            }
        }
        
        /// <remarks/>
        public string Modelo_autosEC {
            get {
                return this.modelo_autosECField;
            }
            set {
                this.modelo_autosECField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo_autosEC {
            get {
                return this.tipo_autosECField;
            }
            set {
                this.tipo_autosECField = value;
            }
        }
        
        /// <remarks/>
        public string Color_autosEC {
            get {
                return this.color_autosECField;
            }
            set {
                this.color_autosECField = value;
            }
        }
        
        /// <remarks/>
        public string Anio_autosEC {
            get {
                return this.anio_autosECField;
            }
            set {
                this.anio_autosECField = value;
            }
        }
        
        /// <remarks/>
        public string Cons_autosEC {
            get {
                return this.cons_autosECField;
            }
            set {
                this.cons_autosECField = value;
            }
        }
        
        /// <remarks/>
        public string img_autosEC {
            get {
                return this.img_autosECField;
            }
            set {
                this.img_autosECField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SeleccionarAutosChevCompletedEventHandler(object sender, SeleccionarAutosChevCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeleccionarAutosChevCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeleccionarAutosChevCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DTOAutosEcuador[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DTOAutosEcuador[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SeleccionarAutosEcuadorPorTipoCompletedEventHandler(object sender, SeleccionarAutosEcuadorPorTipoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeleccionarAutosEcuadorPorTipoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeleccionarAutosEcuadorPorTipoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DTOAutosEcuador[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DTOAutosEcuador[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591