//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiClientes
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class MEMBRESIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEMBRESIA()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
        }
    
        public string MEMID { get; set; }
        public string CLIID { get; set; }
        public string FECHAREGMEM { get; set; }
        public string FECHAEXOMEM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [XmlIgnore]
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        public virtual CLIENTE CLIENTE1 { get; set; }
    }
}
