//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FrontRentaPeliculas.SWRentas {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SWRentasSoap", Namespace="http://tempuri.org/")]
    public partial class SWRentas : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SeleccionarRentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SeleccionarRentaPorIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarRentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarRentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarRentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SeleccionarRentaDefOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SWRentas() {
            this.Url = global::FrontRentaPeliculas.Properties.Settings.Default.FrontRentaPeliculas_SWRentas_SWRentas;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SeleccionarRentaCompletedEventHandler SeleccionarRentaCompleted;
        
        /// <remarks/>
        public event SeleccionarRentaPorIDCompletedEventHandler SeleccionarRentaPorIDCompleted;
        
        /// <remarks/>
        public event InsertarRentaCompletedEventHandler InsertarRentaCompleted;
        
        /// <remarks/>
        public event ActualizarRentaCompletedEventHandler ActualizarRentaCompleted;
        
        /// <remarks/>
        public event EliminarRentaCompletedEventHandler EliminarRentaCompleted;
        
        /// <remarks/>
        public event SeleccionarRentaDefCompletedEventHandler SeleccionarRentaDefCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeleccionarRenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FICHARENTA[] SeleccionarRenta() {
            object[] results = this.Invoke("SeleccionarRenta", new object[0]);
            return ((FICHARENTA[])(results[0]));
        }
        
        /// <remarks/>
        public void SeleccionarRentaAsync() {
            this.SeleccionarRentaAsync(null);
        }
        
        /// <remarks/>
        public void SeleccionarRentaAsync(object userState) {
            if ((this.SeleccionarRentaOperationCompleted == null)) {
                this.SeleccionarRentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeleccionarRentaOperationCompleted);
            }
            this.InvokeAsync("SeleccionarRenta", new object[0], this.SeleccionarRentaOperationCompleted, userState);
        }
        
        private void OnSeleccionarRentaOperationCompleted(object arg) {
            if ((this.SeleccionarRentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeleccionarRentaCompleted(this, new SeleccionarRentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeleccionarRentaPorID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FICHARENTA SeleccionarRentaPorID(string ID) {
            object[] results = this.Invoke("SeleccionarRentaPorID", new object[] {
                        ID});
            return ((FICHARENTA)(results[0]));
        }
        
        /// <remarks/>
        public void SeleccionarRentaPorIDAsync(string ID) {
            this.SeleccionarRentaPorIDAsync(ID, null);
        }
        
        /// <remarks/>
        public void SeleccionarRentaPorIDAsync(string ID, object userState) {
            if ((this.SeleccionarRentaPorIDOperationCompleted == null)) {
                this.SeleccionarRentaPorIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeleccionarRentaPorIDOperationCompleted);
            }
            this.InvokeAsync("SeleccionarRentaPorID", new object[] {
                        ID}, this.SeleccionarRentaPorIDOperationCompleted, userState);
        }
        
        private void OnSeleccionarRentaPorIDOperationCompleted(object arg) {
            if ((this.SeleccionarRentaPorIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeleccionarRentaPorIDCompleted(this, new SeleccionarRentaPorIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertarRenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertarRenta(FICHARENTA ren) {
            this.Invoke("InsertarRenta", new object[] {
                        ren});
        }
        
        /// <remarks/>
        public void InsertarRentaAsync(FICHARENTA ren) {
            this.InsertarRentaAsync(ren, null);
        }
        
        /// <remarks/>
        public void InsertarRentaAsync(FICHARENTA ren, object userState) {
            if ((this.InsertarRentaOperationCompleted == null)) {
                this.InsertarRentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarRentaOperationCompleted);
            }
            this.InvokeAsync("InsertarRenta", new object[] {
                        ren}, this.InsertarRentaOperationCompleted, userState);
        }
        
        private void OnInsertarRentaOperationCompleted(object arg) {
            if ((this.InsertarRentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarRentaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarRenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ActualizarRenta(FICHARENTA ren) {
            object[] results = this.Invoke("ActualizarRenta", new object[] {
                        ren});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarRentaAsync(FICHARENTA ren) {
            this.ActualizarRentaAsync(ren, null);
        }
        
        /// <remarks/>
        public void ActualizarRentaAsync(FICHARENTA ren, object userState) {
            if ((this.ActualizarRentaOperationCompleted == null)) {
                this.ActualizarRentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarRentaOperationCompleted);
            }
            this.InvokeAsync("ActualizarRenta", new object[] {
                        ren}, this.ActualizarRentaOperationCompleted, userState);
        }
        
        private void OnActualizarRentaOperationCompleted(object arg) {
            if ((this.ActualizarRentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarRentaCompleted(this, new ActualizarRentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarRenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarRenta(FICHARENTA ren) {
            object[] results = this.Invoke("EliminarRenta", new object[] {
                        ren});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarRentaAsync(FICHARENTA ren) {
            this.EliminarRentaAsync(ren, null);
        }
        
        /// <remarks/>
        public void EliminarRentaAsync(FICHARENTA ren, object userState) {
            if ((this.EliminarRentaOperationCompleted == null)) {
                this.EliminarRentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarRentaOperationCompleted);
            }
            this.InvokeAsync("EliminarRenta", new object[] {
                        ren}, this.EliminarRentaOperationCompleted, userState);
        }
        
        private void OnEliminarRentaOperationCompleted(object arg) {
            if ((this.EliminarRentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarRentaCompleted(this, new EliminarRentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeleccionarRentaDef", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FICHARENTA[] SeleccionarRentaDef(string ID) {
            object[] results = this.Invoke("SeleccionarRentaDef", new object[] {
                        ID});
            return ((FICHARENTA[])(results[0]));
        }
        
        /// <remarks/>
        public void SeleccionarRentaDefAsync(string ID) {
            this.SeleccionarRentaDefAsync(ID, null);
        }
        
        /// <remarks/>
        public void SeleccionarRentaDefAsync(string ID, object userState) {
            if ((this.SeleccionarRentaDefOperationCompleted == null)) {
                this.SeleccionarRentaDefOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeleccionarRentaDefOperationCompleted);
            }
            this.InvokeAsync("SeleccionarRentaDef", new object[] {
                        ID}, this.SeleccionarRentaDefOperationCompleted, userState);
        }
        
        private void OnSeleccionarRentaDefOperationCompleted(object arg) {
            if ((this.SeleccionarRentaDefCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeleccionarRentaDefCompleted(this, new SeleccionarRentaDefCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FICHARENTA {
        
        private string rENTIDField;
        
        private string pELIIDField;
        
        private string cLIIDField;
        
        private string fECHAREGRENTField;
        
        private string fECHADEVRENTField;
        
        private string fECHAENTRENTField;
        
        private CLIENTE cLIENTEField;
        
        private PELICULA pELICULAField;
        
        /// <remarks/>
        public string RENTID {
            get {
                return this.rENTIDField;
            }
            set {
                this.rENTIDField = value;
            }
        }
        
        /// <remarks/>
        public string PELIID {
            get {
                return this.pELIIDField;
            }
            set {
                this.pELIIDField = value;
            }
        }
        
        /// <remarks/>
        public string CLIID {
            get {
                return this.cLIIDField;
            }
            set {
                this.cLIIDField = value;
            }
        }
        
        /// <remarks/>
        public string FECHAREGRENT {
            get {
                return this.fECHAREGRENTField;
            }
            set {
                this.fECHAREGRENTField = value;
            }
        }
        
        /// <remarks/>
        public string FECHADEVRENT {
            get {
                return this.fECHADEVRENTField;
            }
            set {
                this.fECHADEVRENTField = value;
            }
        }
        
        /// <remarks/>
        public string FECHAENTRENT {
            get {
                return this.fECHAENTRENTField;
            }
            set {
                this.fECHAENTRENTField = value;
            }
        }
        
        /// <remarks/>
        public CLIENTE CLIENTE {
            get {
                return this.cLIENTEField;
            }
            set {
                this.cLIENTEField = value;
            }
        }
        
        /// <remarks/>
        public PELICULA PELICULA {
            get {
                return this.pELICULAField;
            }
            set {
                this.pELICULAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CLIENTE {
        
        private string cLIIDField;
        
        private string mEMIDField;
        
        private string nOMBRECLIField;
        
        private string cEDULACLIField;
        
        private string eMAILCLIField;
        
        private MEMBRESIA mEMBRESIAField;
        
        private FICHARENTA[] fICHARENTAField;
        
        /// <remarks/>
        public string CLIID {
            get {
                return this.cLIIDField;
            }
            set {
                this.cLIIDField = value;
            }
        }
        
        /// <remarks/>
        public string MEMID {
            get {
                return this.mEMIDField;
            }
            set {
                this.mEMIDField = value;
            }
        }
        
        /// <remarks/>
        public string NOMBRECLI {
            get {
                return this.nOMBRECLIField;
            }
            set {
                this.nOMBRECLIField = value;
            }
        }
        
        /// <remarks/>
        public string CEDULACLI {
            get {
                return this.cEDULACLIField;
            }
            set {
                this.cEDULACLIField = value;
            }
        }
        
        /// <remarks/>
        public string EMAILCLI {
            get {
                return this.eMAILCLIField;
            }
            set {
                this.eMAILCLIField = value;
            }
        }
        
        /// <remarks/>
        public MEMBRESIA MEMBRESIA {
            get {
                return this.mEMBRESIAField;
            }
            set {
                this.mEMBRESIAField = value;
            }
        }
        
        /// <remarks/>
        public FICHARENTA[] FICHARENTA {
            get {
                return this.fICHARENTAField;
            }
            set {
                this.fICHARENTAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MEMBRESIA {
        
        private string mEMIDField;
        
        private string cLIIDField;
        
        private string fECHAREGMEMField;
        
        private string fECHAEXOMEMField;
        
        private CLIENTE cLIENTE1Field;
        
        /// <remarks/>
        public string MEMID {
            get {
                return this.mEMIDField;
            }
            set {
                this.mEMIDField = value;
            }
        }
        
        /// <remarks/>
        public string CLIID {
            get {
                return this.cLIIDField;
            }
            set {
                this.cLIIDField = value;
            }
        }
        
        /// <remarks/>
        public string FECHAREGMEM {
            get {
                return this.fECHAREGMEMField;
            }
            set {
                this.fECHAREGMEMField = value;
            }
        }
        
        /// <remarks/>
        public string FECHAEXOMEM {
            get {
                return this.fECHAEXOMEMField;
            }
            set {
                this.fECHAEXOMEMField = value;
            }
        }
        
        /// <remarks/>
        public CLIENTE CLIENTE1 {
            get {
                return this.cLIENTE1Field;
            }
            set {
                this.cLIENTE1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PELICULA {
        
        private string pELIIDField;
        
        private string nOMBREPELIField;
        
        private string dIRECTORPELIField;
        
        private string gENEROPELIField;
        
        private FICHARENTA[] fICHARENTAField;
        
        /// <remarks/>
        public string PELIID {
            get {
                return this.pELIIDField;
            }
            set {
                this.pELIIDField = value;
            }
        }
        
        /// <remarks/>
        public string NOMBREPELI {
            get {
                return this.nOMBREPELIField;
            }
            set {
                this.nOMBREPELIField = value;
            }
        }
        
        /// <remarks/>
        public string DIRECTORPELI {
            get {
                return this.dIRECTORPELIField;
            }
            set {
                this.dIRECTORPELIField = value;
            }
        }
        
        /// <remarks/>
        public string GENEROPELI {
            get {
                return this.gENEROPELIField;
            }
            set {
                this.gENEROPELIField = value;
            }
        }
        
        /// <remarks/>
        public FICHARENTA[] FICHARENTA {
            get {
                return this.fICHARENTAField;
            }
            set {
                this.fICHARENTAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SeleccionarRentaCompletedEventHandler(object sender, SeleccionarRentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeleccionarRentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeleccionarRentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FICHARENTA[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FICHARENTA[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SeleccionarRentaPorIDCompletedEventHandler(object sender, SeleccionarRentaPorIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeleccionarRentaPorIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeleccionarRentaPorIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FICHARENTA Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FICHARENTA)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void InsertarRentaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ActualizarRentaCompletedEventHandler(object sender, ActualizarRentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarRentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarRentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EliminarRentaCompletedEventHandler(object sender, EliminarRentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarRentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarRentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SeleccionarRentaDefCompletedEventHandler(object sender, SeleccionarRentaDefCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeleccionarRentaDefCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeleccionarRentaDefCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FICHARENTA[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FICHARENTA[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591