//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class FICHARENTA
    {
        public string RENTID { get; set; }
        public string PELIID { get; set; }
        public string CLIID { get; set; }
        public string FECHAREGRENT { get; set; }
        public string FECHADEVRENT { get; set; }
        public string FECHAENTRENT { get; set; }

        public virtual CLIENTE CLIENTE { get; set; }
        public virtual PELICULA PELICULA { get; set; }
    }
}
