//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FrontRentaPeliculas.SWMembresias {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SWMembresiasSoap", Namespace="http://tempuri.org/")]
    public partial class SWMembresias : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SeleccionarMembresiasOperationCompleted;
        
        private System.Threading.SendOrPostCallback SeleccionarMembresiaPorIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarMembresiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarMembresiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarMembresiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SeleccionarMembresiasDefOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SWMembresias() {
            this.Url = global::FrontRentaPeliculas.Properties.Settings.Default.FrontRentaPeliculas_SWMembresias_SWMembresias;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SeleccionarMembresiasCompletedEventHandler SeleccionarMembresiasCompleted;
        
        /// <remarks/>
        public event SeleccionarMembresiaPorIDCompletedEventHandler SeleccionarMembresiaPorIDCompleted;
        
        /// <remarks/>
        public event InsertarMembresiaCompletedEventHandler InsertarMembresiaCompleted;
        
        /// <remarks/>
        public event ActualizarMembresiaCompletedEventHandler ActualizarMembresiaCompleted;
        
        /// <remarks/>
        public event EliminarMembresiaCompletedEventHandler EliminarMembresiaCompleted;
        
        /// <remarks/>
        public event SeleccionarMembresiasDefCompletedEventHandler SeleccionarMembresiasDefCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeleccionarMembresias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MEMBRESIA[] SeleccionarMembresias() {
            object[] results = this.Invoke("SeleccionarMembresias", new object[0]);
            return ((MEMBRESIA[])(results[0]));
        }
        
        /// <remarks/>
        public void SeleccionarMembresiasAsync() {
            this.SeleccionarMembresiasAsync(null);
        }
        
        /// <remarks/>
        public void SeleccionarMembresiasAsync(object userState) {
            if ((this.SeleccionarMembresiasOperationCompleted == null)) {
                this.SeleccionarMembresiasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeleccionarMembresiasOperationCompleted);
            }
            this.InvokeAsync("SeleccionarMembresias", new object[0], this.SeleccionarMembresiasOperationCompleted, userState);
        }
        
        private void OnSeleccionarMembresiasOperationCompleted(object arg) {
            if ((this.SeleccionarMembresiasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeleccionarMembresiasCompleted(this, new SeleccionarMembresiasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeleccionarMembresiaPorID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MEMBRESIA SeleccionarMembresiaPorID(string ID) {
            object[] results = this.Invoke("SeleccionarMembresiaPorID", new object[] {
                        ID});
            return ((MEMBRESIA)(results[0]));
        }
        
        /// <remarks/>
        public void SeleccionarMembresiaPorIDAsync(string ID) {
            this.SeleccionarMembresiaPorIDAsync(ID, null);
        }
        
        /// <remarks/>
        public void SeleccionarMembresiaPorIDAsync(string ID, object userState) {
            if ((this.SeleccionarMembresiaPorIDOperationCompleted == null)) {
                this.SeleccionarMembresiaPorIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeleccionarMembresiaPorIDOperationCompleted);
            }
            this.InvokeAsync("SeleccionarMembresiaPorID", new object[] {
                        ID}, this.SeleccionarMembresiaPorIDOperationCompleted, userState);
        }
        
        private void OnSeleccionarMembresiaPorIDOperationCompleted(object arg) {
            if ((this.SeleccionarMembresiaPorIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeleccionarMembresiaPorIDCompleted(this, new SeleccionarMembresiaPorIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertarMembresia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertarMembresia(MEMBRESIA cli) {
            this.Invoke("InsertarMembresia", new object[] {
                        cli});
        }
        
        /// <remarks/>
        public void InsertarMembresiaAsync(MEMBRESIA cli) {
            this.InsertarMembresiaAsync(cli, null);
        }
        
        /// <remarks/>
        public void InsertarMembresiaAsync(MEMBRESIA cli, object userState) {
            if ((this.InsertarMembresiaOperationCompleted == null)) {
                this.InsertarMembresiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarMembresiaOperationCompleted);
            }
            this.InvokeAsync("InsertarMembresia", new object[] {
                        cli}, this.InsertarMembresiaOperationCompleted, userState);
        }
        
        private void OnInsertarMembresiaOperationCompleted(object arg) {
            if ((this.InsertarMembresiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarMembresiaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarMembresia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ActualizarMembresia(MEMBRESIA cli) {
            object[] results = this.Invoke("ActualizarMembresia", new object[] {
                        cli});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarMembresiaAsync(MEMBRESIA cli) {
            this.ActualizarMembresiaAsync(cli, null);
        }
        
        /// <remarks/>
        public void ActualizarMembresiaAsync(MEMBRESIA cli, object userState) {
            if ((this.ActualizarMembresiaOperationCompleted == null)) {
                this.ActualizarMembresiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarMembresiaOperationCompleted);
            }
            this.InvokeAsync("ActualizarMembresia", new object[] {
                        cli}, this.ActualizarMembresiaOperationCompleted, userState);
        }
        
        private void OnActualizarMembresiaOperationCompleted(object arg) {
            if ((this.ActualizarMembresiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarMembresiaCompleted(this, new ActualizarMembresiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarMembresia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarMembresia(MEMBRESIA cli) {
            object[] results = this.Invoke("EliminarMembresia", new object[] {
                        cli});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarMembresiaAsync(MEMBRESIA cli) {
            this.EliminarMembresiaAsync(cli, null);
        }
        
        /// <remarks/>
        public void EliminarMembresiaAsync(MEMBRESIA cli, object userState) {
            if ((this.EliminarMembresiaOperationCompleted == null)) {
                this.EliminarMembresiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarMembresiaOperationCompleted);
            }
            this.InvokeAsync("EliminarMembresia", new object[] {
                        cli}, this.EliminarMembresiaOperationCompleted, userState);
        }
        
        private void OnEliminarMembresiaOperationCompleted(object arg) {
            if ((this.EliminarMembresiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarMembresiaCompleted(this, new EliminarMembresiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeleccionarMembresiasDef", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MEMBRESIA[] SeleccionarMembresiasDef(string ID) {
            object[] results = this.Invoke("SeleccionarMembresiasDef", new object[] {
                        ID});
            return ((MEMBRESIA[])(results[0]));
        }
        
        /// <remarks/>
        public void SeleccionarMembresiasDefAsync(string ID) {
            this.SeleccionarMembresiasDefAsync(ID, null);
        }
        
        /// <remarks/>
        public void SeleccionarMembresiasDefAsync(string ID, object userState) {
            if ((this.SeleccionarMembresiasDefOperationCompleted == null)) {
                this.SeleccionarMembresiasDefOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeleccionarMembresiasDefOperationCompleted);
            }
            this.InvokeAsync("SeleccionarMembresiasDef", new object[] {
                        ID}, this.SeleccionarMembresiasDefOperationCompleted, userState);
        }
        
        private void OnSeleccionarMembresiasDefOperationCompleted(object arg) {
            if ((this.SeleccionarMembresiasDefCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeleccionarMembresiasDefCompleted(this, new SeleccionarMembresiasDefCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MEMBRESIA {
        
        private string mEMIDField;
        
        private string cLIIDField;
        
        private string fECHAREGMEMField;
        
        private string fECHAEXOMEMField;
        
        private CLIENTE cLIENTE1Field;
        
        /// <remarks/>
        public string MEMID {
            get {
                return this.mEMIDField;
            }
            set {
                this.mEMIDField = value;
            }
        }
        
        /// <remarks/>
        public string CLIID {
            get {
                return this.cLIIDField;
            }
            set {
                this.cLIIDField = value;
            }
        }
        
        /// <remarks/>
        public string FECHAREGMEM {
            get {
                return this.fECHAREGMEMField;
            }
            set {
                this.fECHAREGMEMField = value;
            }
        }
        
        /// <remarks/>
        public string FECHAEXOMEM {
            get {
                return this.fECHAEXOMEMField;
            }
            set {
                this.fECHAEXOMEMField = value;
            }
        }
        
        /// <remarks/>
        public CLIENTE CLIENTE1 {
            get {
                return this.cLIENTE1Field;
            }
            set {
                this.cLIENTE1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CLIENTE {
        
        private string cLIIDField;
        
        private string mEMIDField;
        
        private string nOMBRECLIField;
        
        private string cEDULACLIField;
        
        private string eMAILCLIField;
        
        private MEMBRESIA mEMBRESIAField;
        
        private FICHARENTA[] fICHARENTAField;
        
        /// <remarks/>
        public string CLIID {
            get {
                return this.cLIIDField;
            }
            set {
                this.cLIIDField = value;
            }
        }
        
        /// <remarks/>
        public string MEMID {
            get {
                return this.mEMIDField;
            }
            set {
                this.mEMIDField = value;
            }
        }
        
        /// <remarks/>
        public string NOMBRECLI {
            get {
                return this.nOMBRECLIField;
            }
            set {
                this.nOMBRECLIField = value;
            }
        }
        
        /// <remarks/>
        public string CEDULACLI {
            get {
                return this.cEDULACLIField;
            }
            set {
                this.cEDULACLIField = value;
            }
        }
        
        /// <remarks/>
        public string EMAILCLI {
            get {
                return this.eMAILCLIField;
            }
            set {
                this.eMAILCLIField = value;
            }
        }
        
        /// <remarks/>
        public MEMBRESIA MEMBRESIA {
            get {
                return this.mEMBRESIAField;
            }
            set {
                this.mEMBRESIAField = value;
            }
        }
        
        /// <remarks/>
        public FICHARENTA[] FICHARENTA {
            get {
                return this.fICHARENTAField;
            }
            set {
                this.fICHARENTAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FICHARENTA {
        
        private string rENTIDField;
        
        private string pELIIDField;
        
        private string cLIIDField;
        
        private string fECHAREGRENTField;
        
        private string fECHADEVRENTField;
        
        private string fECHAENTRENTField;
        
        private CLIENTE cLIENTEField;
        
        private PELICULA pELICULAField;
        
        /// <remarks/>
        public string RENTID {
            get {
                return this.rENTIDField;
            }
            set {
                this.rENTIDField = value;
            }
        }
        
        /// <remarks/>
        public string PELIID {
            get {
                return this.pELIIDField;
            }
            set {
                this.pELIIDField = value;
            }
        }
        
        /// <remarks/>
        public string CLIID {
            get {
                return this.cLIIDField;
            }
            set {
                this.cLIIDField = value;
            }
        }
        
        /// <remarks/>
        public string FECHAREGRENT {
            get {
                return this.fECHAREGRENTField;
            }
            set {
                this.fECHAREGRENTField = value;
            }
        }
        
        /// <remarks/>
        public string FECHADEVRENT {
            get {
                return this.fECHADEVRENTField;
            }
            set {
                this.fECHADEVRENTField = value;
            }
        }
        
        /// <remarks/>
        public string FECHAENTRENT {
            get {
                return this.fECHAENTRENTField;
            }
            set {
                this.fECHAENTRENTField = value;
            }
        }
        
        /// <remarks/>
        public CLIENTE CLIENTE {
            get {
                return this.cLIENTEField;
            }
            set {
                this.cLIENTEField = value;
            }
        }
        
        /// <remarks/>
        public PELICULA PELICULA {
            get {
                return this.pELICULAField;
            }
            set {
                this.pELICULAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PELICULA {
        
        private string pELIIDField;
        
        private string nOMBREPELIField;
        
        private string dIRECTORPELIField;
        
        private string gENEROPELIField;
        
        private FICHARENTA[] fICHARENTAField;
        
        /// <remarks/>
        public string PELIID {
            get {
                return this.pELIIDField;
            }
            set {
                this.pELIIDField = value;
            }
        }
        
        /// <remarks/>
        public string NOMBREPELI {
            get {
                return this.nOMBREPELIField;
            }
            set {
                this.nOMBREPELIField = value;
            }
        }
        
        /// <remarks/>
        public string DIRECTORPELI {
            get {
                return this.dIRECTORPELIField;
            }
            set {
                this.dIRECTORPELIField = value;
            }
        }
        
        /// <remarks/>
        public string GENEROPELI {
            get {
                return this.gENEROPELIField;
            }
            set {
                this.gENEROPELIField = value;
            }
        }
        
        /// <remarks/>
        public FICHARENTA[] FICHARENTA {
            get {
                return this.fICHARENTAField;
            }
            set {
                this.fICHARENTAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SeleccionarMembresiasCompletedEventHandler(object sender, SeleccionarMembresiasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeleccionarMembresiasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeleccionarMembresiasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MEMBRESIA[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MEMBRESIA[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SeleccionarMembresiaPorIDCompletedEventHandler(object sender, SeleccionarMembresiaPorIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeleccionarMembresiaPorIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeleccionarMembresiaPorIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MEMBRESIA Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MEMBRESIA)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void InsertarMembresiaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ActualizarMembresiaCompletedEventHandler(object sender, ActualizarMembresiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarMembresiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarMembresiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EliminarMembresiaCompletedEventHandler(object sender, EliminarMembresiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarMembresiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarMembresiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SeleccionarMembresiasDefCompletedEventHandler(object sender, SeleccionarMembresiasDefCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeleccionarMembresiasDefCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeleccionarMembresiasDefCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MEMBRESIA[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MEMBRESIA[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591