//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto_FORD
    {
        public int id { get; set; }
        public string Marca_Ford { get; set; }
        public string Modelo_Ford { get; set; }
        public string Cilindraje_Ford { get; set; }
        public string Anio_Ford { get; set; }
        public string Color_Ford { get; set; }
        public string Tipo_Ford { get; set; }
        public string Con_Ford { get; set; }
        public string Fecha_Ford { get; set; }
        public string img_Ford { get; set; }
    }
}
