//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWRentaPeliculasBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBRESIA
    {
       
    
        public string MEMID { get; set; }
        public string CLIID { get; set; }
        public string FECHAREGMEM { get; set; }
        public string FECHAEXOMEM { get; set; }
    
      
    }
}
