//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWRentaPeliculasBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RentaPeliculasEntities : DbContext
    {
        public RentaPeliculasEntities()
            : base("name=RentaPeliculasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<FICHARENTA> FICHARENTA { get; set; }
        public virtual DbSet<MEMBRESIA> MEMBRESIA { get; set; }
        public virtual DbSet<PELICULA> PELICULA { get; set; }
    
        public virtual ObjectResult<SeleccionarClientes_Result> SeleccionarClientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SeleccionarClientes_Result>("SeleccionarClientes");
        }
    
        public virtual ObjectResult<SeleccionarClientesPorID_Result> SeleccionarClientesPorID(Nullable<int> cLIID)
        {
            var cLIIDParameter = cLIID.HasValue ?
                new ObjectParameter("CLIID", cLIID) :
                new ObjectParameter("CLIID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SeleccionarClientesPorID_Result>("SeleccionarClientesPorID", cLIIDParameter);
        }
    
        public virtual int ActualizarClienteSP(string cLIID, string nOMBRECLI, string cEDULACLI, string eMAILCLI)
        {
            var cLIIDParameter = cLIID != null ?
                new ObjectParameter("CLIID", cLIID) :
                new ObjectParameter("CLIID", typeof(string));
    
            var nOMBRECLIParameter = nOMBRECLI != null ?
                new ObjectParameter("NOMBRECLI", nOMBRECLI) :
                new ObjectParameter("NOMBRECLI", typeof(string));
    
            var cEDULACLIParameter = cEDULACLI != null ?
                new ObjectParameter("CEDULACLI", cEDULACLI) :
                new ObjectParameter("CEDULACLI", typeof(string));
    
            var eMAILCLIParameter = eMAILCLI != null ?
                new ObjectParameter("EMAILCLI", eMAILCLI) :
                new ObjectParameter("EMAILCLI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarClienteSP", cLIIDParameter, nOMBRECLIParameter, cEDULACLIParameter, eMAILCLIParameter);
        }
    
        public virtual int EliminarClienteSP(string cLIID)
        {
            var cLIIDParameter = cLIID != null ?
                new ObjectParameter("CLIID", cLIID) :
                new ObjectParameter("CLIID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarClienteSP", cLIIDParameter);
        }
    
        public virtual int InsertarClienteSP(string cLIID, string nOMBRECLI, string cEDULACLI, string eMAILCLI, string mEMID)
        {
            var cLIIDParameter = cLIID != null ?
                new ObjectParameter("CLIID", cLIID) :
                new ObjectParameter("CLIID", typeof(string));
    
            var nOMBRECLIParameter = nOMBRECLI != null ?
                new ObjectParameter("NOMBRECLI", nOMBRECLI) :
                new ObjectParameter("NOMBRECLI", typeof(string));
    
            var cEDULACLIParameter = cEDULACLI != null ?
                new ObjectParameter("CEDULACLI", cEDULACLI) :
                new ObjectParameter("CEDULACLI", typeof(string));
    
            var eMAILCLIParameter = eMAILCLI != null ?
                new ObjectParameter("EMAILCLI", eMAILCLI) :
                new ObjectParameter("EMAILCLI", typeof(string));
    
            var mEMIDParameter = mEMID != null ?
                new ObjectParameter("MEMID", mEMID) :
                new ObjectParameter("MEMID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarClienteSP", cLIIDParameter, nOMBRECLIParameter, cEDULACLIParameter, eMAILCLIParameter, mEMIDParameter);
        }
    
        public virtual ObjectResult<SeleccionarClientePorID_Result> SeleccionarClientePorID(string cLIID)
        {
            var cLIIDParameter = cLIID != null ?
                new ObjectParameter("CLIID", cLIID) :
                new ObjectParameter("CLIID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SeleccionarClientePorID_Result>("SeleccionarClientePorID", cLIIDParameter);
        }
    
        public virtual int ActualizarMembresiaSP(string mEMID, string cLIID, string fECHAREGMEM, string fECHAEXOMEM)
        {
            var mEMIDParameter = mEMID != null ?
                new ObjectParameter("MEMID", mEMID) :
                new ObjectParameter("MEMID", typeof(string));
    
            var cLIIDParameter = cLIID != null ?
                new ObjectParameter("CLIID", cLIID) :
                new ObjectParameter("CLIID", typeof(string));
    
            var fECHAREGMEMParameter = fECHAREGMEM != null ?
                new ObjectParameter("FECHAREGMEM", fECHAREGMEM) :
                new ObjectParameter("FECHAREGMEM", typeof(string));
    
            var fECHAEXOMEMParameter = fECHAEXOMEM != null ?
                new ObjectParameter("FECHAEXOMEM", fECHAEXOMEM) :
                new ObjectParameter("FECHAEXOMEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarMembresiaSP", mEMIDParameter, cLIIDParameter, fECHAREGMEMParameter, fECHAEXOMEMParameter);
        }
    
        public virtual int ActualizarPeliculaSP(string pELID, string nOMPEL, string dIRPEL, string gENPEL)
        {
            var pELIDParameter = pELID != null ?
                new ObjectParameter("PELID", pELID) :
                new ObjectParameter("PELID", typeof(string));
    
            var nOMPELParameter = nOMPEL != null ?
                new ObjectParameter("NOMPEL", nOMPEL) :
                new ObjectParameter("NOMPEL", typeof(string));
    
            var dIRPELParameter = dIRPEL != null ?
                new ObjectParameter("DIRPEL", dIRPEL) :
                new ObjectParameter("DIRPEL", typeof(string));
    
            var gENPELParameter = gENPEL != null ?
                new ObjectParameter("GENPEL", gENPEL) :
                new ObjectParameter("GENPEL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarPeliculaSP", pELIDParameter, nOMPELParameter, dIRPELParameter, gENPELParameter);
        }
    
        public virtual int ActualizarRentaSP(string rENID, string pELID, string cLID, string fECHA1, string fECHA2, string fECHA3)
        {
            var rENIDParameter = rENID != null ?
                new ObjectParameter("RENID", rENID) :
                new ObjectParameter("RENID", typeof(string));
    
            var pELIDParameter = pELID != null ?
                new ObjectParameter("PELID", pELID) :
                new ObjectParameter("PELID", typeof(string));
    
            var cLIDParameter = cLID != null ?
                new ObjectParameter("CLID", cLID) :
                new ObjectParameter("CLID", typeof(string));
    
            var fECHA1Parameter = fECHA1 != null ?
                new ObjectParameter("FECHA1", fECHA1) :
                new ObjectParameter("FECHA1", typeof(string));
    
            var fECHA2Parameter = fECHA2 != null ?
                new ObjectParameter("FECHA2", fECHA2) :
                new ObjectParameter("FECHA2", typeof(string));
    
            var fECHA3Parameter = fECHA3 != null ?
                new ObjectParameter("FECHA3", fECHA3) :
                new ObjectParameter("FECHA3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarRentaSP", rENIDParameter, pELIDParameter, cLIDParameter, fECHA1Parameter, fECHA2Parameter, fECHA3Parameter);
        }
    
        public virtual int EliminarMembresiaSP(string mEMID)
        {
            var mEMIDParameter = mEMID != null ?
                new ObjectParameter("MEMID", mEMID) :
                new ObjectParameter("MEMID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarMembresiaSP", mEMIDParameter);
        }
    
        public virtual int EliminarPeliculaSP(string pELID)
        {
            var pELIDParameter = pELID != null ?
                new ObjectParameter("PELID", pELID) :
                new ObjectParameter("PELID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarPeliculaSP", pELIDParameter);
        }
    
        public virtual int EliminarRentaSP(string rENID)
        {
            var rENIDParameter = rENID != null ?
                new ObjectParameter("RENID", rENID) :
                new ObjectParameter("RENID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarRentaSP", rENIDParameter);
        }
    
        public virtual int InsertarMembresiaSP(string mEMID, string cLIID, string fECHAREGMEM, string fECHAEXOMEM)
        {
            var mEMIDParameter = mEMID != null ?
                new ObjectParameter("MEMID", mEMID) :
                new ObjectParameter("MEMID", typeof(string));
    
            var cLIIDParameter = cLIID != null ?
                new ObjectParameter("CLIID", cLIID) :
                new ObjectParameter("CLIID", typeof(string));
    
            var fECHAREGMEMParameter = fECHAREGMEM != null ?
                new ObjectParameter("FECHAREGMEM", fECHAREGMEM) :
                new ObjectParameter("FECHAREGMEM", typeof(string));
    
            var fECHAEXOMEMParameter = fECHAEXOMEM != null ?
                new ObjectParameter("FECHAEXOMEM", fECHAEXOMEM) :
                new ObjectParameter("FECHAEXOMEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarMembresiaSP", mEMIDParameter, cLIIDParameter, fECHAREGMEMParameter, fECHAEXOMEMParameter);
        }
    
        public virtual int InsertarPeliculaSP(string pELID, string nOMPEL, string dIRPEL, string gENPEL)
        {
            var pELIDParameter = pELID != null ?
                new ObjectParameter("PELID", pELID) :
                new ObjectParameter("PELID", typeof(string));
    
            var nOMPELParameter = nOMPEL != null ?
                new ObjectParameter("NOMPEL", nOMPEL) :
                new ObjectParameter("NOMPEL", typeof(string));
    
            var dIRPELParameter = dIRPEL != null ?
                new ObjectParameter("DIRPEL", dIRPEL) :
                new ObjectParameter("DIRPEL", typeof(string));
    
            var gENPELParameter = gENPEL != null ?
                new ObjectParameter("GENPEL", gENPEL) :
                new ObjectParameter("GENPEL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarPeliculaSP", pELIDParameter, nOMPELParameter, dIRPELParameter, gENPELParameter);
        }
    
        public virtual int InsertarRentaSP(string rENID, string pELID, string cLID, string fECHA1, string fECHA2, string fECHA3)
        {
            var rENIDParameter = rENID != null ?
                new ObjectParameter("RENID", rENID) :
                new ObjectParameter("RENID", typeof(string));
    
            var pELIDParameter = pELID != null ?
                new ObjectParameter("PELID", pELID) :
                new ObjectParameter("PELID", typeof(string));
    
            var cLIDParameter = cLID != null ?
                new ObjectParameter("CLID", cLID) :
                new ObjectParameter("CLID", typeof(string));
    
            var fECHA1Parameter = fECHA1 != null ?
                new ObjectParameter("FECHA1", fECHA1) :
                new ObjectParameter("FECHA1", typeof(string));
    
            var fECHA2Parameter = fECHA2 != null ?
                new ObjectParameter("FECHA2", fECHA2) :
                new ObjectParameter("FECHA2", typeof(string));
    
            var fECHA3Parameter = fECHA3 != null ?
                new ObjectParameter("FECHA3", fECHA3) :
                new ObjectParameter("FECHA3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarRentaSP", rENIDParameter, pELIDParameter, cLIDParameter, fECHA1Parameter, fECHA2Parameter, fECHA3Parameter);
        }
    
        public virtual ObjectResult<SeleccionarMembresiasSP_Result> SeleccionarMembresiasSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SeleccionarMembresiasSP_Result>("SeleccionarMembresiasSP");
        }
    
        public virtual ObjectResult<SeleccionarPeliculasSP_Result> SeleccionarPeliculasSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SeleccionarPeliculasSP_Result>("SeleccionarPeliculasSP");
        }
    
        public virtual ObjectResult<SeleccionarRentasSP_Result> SeleccionarRentasSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SeleccionarRentasSP_Result>("SeleccionarRentasSP");
        }
    }
}
