//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Front.Clientes {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SWClientesSoap", Namespace="http://tempuri.org/")]
    public partial class SWClientes : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SeleccionarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback SeleccionarClientePorIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback SeleccionarClientesDefOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SWClientes() {
            this.Url = global::Front.Properties.Settings.Default.Front_Clientes_SWClientes;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SeleccionarClienteCompletedEventHandler SeleccionarClienteCompleted;
        
        /// <remarks/>
        public event SeleccionarClientePorIDCompletedEventHandler SeleccionarClientePorIDCompleted;
        
        /// <remarks/>
        public event InsertarClienteCompletedEventHandler InsertarClienteCompleted;
        
        /// <remarks/>
        public event ActualizarClienteCompletedEventHandler ActualizarClienteCompleted;
        
        /// <remarks/>
        public event EliminarClienteCompletedEventHandler EliminarClienteCompleted;
        
        /// <remarks/>
        public event SeleccionarClientesDefCompletedEventHandler SeleccionarClientesDefCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeleccionarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CLIENTE[] SeleccionarCliente() {
            object[] results = this.Invoke("SeleccionarCliente", new object[0]);
            return ((CLIENTE[])(results[0]));
        }
        
        /// <remarks/>
        public void SeleccionarClienteAsync() {
            this.SeleccionarClienteAsync(null);
        }
        
        /// <remarks/>
        public void SeleccionarClienteAsync(object userState) {
            if ((this.SeleccionarClienteOperationCompleted == null)) {
                this.SeleccionarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeleccionarClienteOperationCompleted);
            }
            this.InvokeAsync("SeleccionarCliente", new object[0], this.SeleccionarClienteOperationCompleted, userState);
        }
        
        private void OnSeleccionarClienteOperationCompleted(object arg) {
            if ((this.SeleccionarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeleccionarClienteCompleted(this, new SeleccionarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeleccionarClientePorID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CLIENTE SeleccionarClientePorID(string ID) {
            object[] results = this.Invoke("SeleccionarClientePorID", new object[] {
                        ID});
            return ((CLIENTE)(results[0]));
        }
        
        /// <remarks/>
        public void SeleccionarClientePorIDAsync(string ID) {
            this.SeleccionarClientePorIDAsync(ID, null);
        }
        
        /// <remarks/>
        public void SeleccionarClientePorIDAsync(string ID, object userState) {
            if ((this.SeleccionarClientePorIDOperationCompleted == null)) {
                this.SeleccionarClientePorIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeleccionarClientePorIDOperationCompleted);
            }
            this.InvokeAsync("SeleccionarClientePorID", new object[] {
                        ID}, this.SeleccionarClientePorIDOperationCompleted, userState);
        }
        
        private void OnSeleccionarClientePorIDOperationCompleted(object arg) {
            if ((this.SeleccionarClientePorIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeleccionarClientePorIDCompleted(this, new SeleccionarClientePorIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertarCliente(CLIENTE cli) {
            this.Invoke("InsertarCliente", new object[] {
                        cli});
        }
        
        /// <remarks/>
        public void InsertarClienteAsync(CLIENTE cli) {
            this.InsertarClienteAsync(cli, null);
        }
        
        /// <remarks/>
        public void InsertarClienteAsync(CLIENTE cli, object userState) {
            if ((this.InsertarClienteOperationCompleted == null)) {
                this.InsertarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarClienteOperationCompleted);
            }
            this.InvokeAsync("InsertarCliente", new object[] {
                        cli}, this.InsertarClienteOperationCompleted, userState);
        }
        
        private void OnInsertarClienteOperationCompleted(object arg) {
            if ((this.InsertarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ActualizarCliente(CLIENTE cli) {
            object[] results = this.Invoke("ActualizarCliente", new object[] {
                        cli});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarClienteAsync(CLIENTE cli) {
            this.ActualizarClienteAsync(cli, null);
        }
        
        /// <remarks/>
        public void ActualizarClienteAsync(CLIENTE cli, object userState) {
            if ((this.ActualizarClienteOperationCompleted == null)) {
                this.ActualizarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarClienteOperationCompleted);
            }
            this.InvokeAsync("ActualizarCliente", new object[] {
                        cli}, this.ActualizarClienteOperationCompleted, userState);
        }
        
        private void OnActualizarClienteOperationCompleted(object arg) {
            if ((this.ActualizarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarClienteCompleted(this, new ActualizarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarCliente(CLIENTE cli) {
            object[] results = this.Invoke("EliminarCliente", new object[] {
                        cli});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarClienteAsync(CLIENTE cli) {
            this.EliminarClienteAsync(cli, null);
        }
        
        /// <remarks/>
        public void EliminarClienteAsync(CLIENTE cli, object userState) {
            if ((this.EliminarClienteOperationCompleted == null)) {
                this.EliminarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarClienteOperationCompleted);
            }
            this.InvokeAsync("EliminarCliente", new object[] {
                        cli}, this.EliminarClienteOperationCompleted, userState);
        }
        
        private void OnEliminarClienteOperationCompleted(object arg) {
            if ((this.EliminarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarClienteCompleted(this, new EliminarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeleccionarClientesDef", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CLIENTE[] SeleccionarClientesDef(string ID) {
            object[] results = this.Invoke("SeleccionarClientesDef", new object[] {
                        ID});
            return ((CLIENTE[])(results[0]));
        }
        
        /// <remarks/>
        public void SeleccionarClientesDefAsync(string ID) {
            this.SeleccionarClientesDefAsync(ID, null);
        }
        
        /// <remarks/>
        public void SeleccionarClientesDefAsync(string ID, object userState) {
            if ((this.SeleccionarClientesDefOperationCompleted == null)) {
                this.SeleccionarClientesDefOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeleccionarClientesDefOperationCompleted);
            }
            this.InvokeAsync("SeleccionarClientesDef", new object[] {
                        ID}, this.SeleccionarClientesDefOperationCompleted, userState);
        }
        
        private void OnSeleccionarClientesDefOperationCompleted(object arg) {
            if ((this.SeleccionarClientesDefCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeleccionarClientesDefCompleted(this, new SeleccionarClientesDefCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CLIENTE {
        
        private string cLIIDField;
        
        private string mEMIDField;
        
        private string nOMBRECLIField;
        
        private string cEDULACLIField;
        
        private string eMAILCLIField;
        
        private MEMBRESIA mEMBRESIAField;
        
        private FICHARENTA[] fICHARENTAField;
        
        /// <remarks/>
        public string CLIID {
            get {
                return this.cLIIDField;
            }
            set {
                this.cLIIDField = value;
            }
        }
        
        /// <remarks/>
        public string MEMID {
            get {
                return this.mEMIDField;
            }
            set {
                this.mEMIDField = value;
            }
        }
        
        /// <remarks/>
        public string NOMBRECLI {
            get {
                return this.nOMBRECLIField;
            }
            set {
                this.nOMBRECLIField = value;
            }
        }
        
        /// <remarks/>
        public string CEDULACLI {
            get {
                return this.cEDULACLIField;
            }
            set {
                this.cEDULACLIField = value;
            }
        }
        
        /// <remarks/>
        public string EMAILCLI {
            get {
                return this.eMAILCLIField;
            }
            set {
                this.eMAILCLIField = value;
            }
        }
        
        /// <remarks/>
        public MEMBRESIA MEMBRESIA {
            get {
                return this.mEMBRESIAField;
            }
            set {
                this.mEMBRESIAField = value;
            }
        }
        
        /// <remarks/>
        public FICHARENTA[] FICHARENTA {
            get {
                return this.fICHARENTAField;
            }
            set {
                this.fICHARENTAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MEMBRESIA {
        
        private string mEMIDField;
        
        private string cLIIDField;
        
        private string fECHAREGMEMField;
        
        private string fECHAEXOMEMField;
        
        private CLIENTE cLIENTE1Field;
        
        /// <remarks/>
        public string MEMID {
            get {
                return this.mEMIDField;
            }
            set {
                this.mEMIDField = value;
            }
        }
        
        /// <remarks/>
        public string CLIID {
            get {
                return this.cLIIDField;
            }
            set {
                this.cLIIDField = value;
            }
        }
        
        /// <remarks/>
        public string FECHAREGMEM {
            get {
                return this.fECHAREGMEMField;
            }
            set {
                this.fECHAREGMEMField = value;
            }
        }
        
        /// <remarks/>
        public string FECHAEXOMEM {
            get {
                return this.fECHAEXOMEMField;
            }
            set {
                this.fECHAEXOMEMField = value;
            }
        }
        
        /// <remarks/>
        public CLIENTE CLIENTE1 {
            get {
                return this.cLIENTE1Field;
            }
            set {
                this.cLIENTE1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PELICULA {
        
        private string pELIIDField;
        
        private string nOMBREPELIField;
        
        private string dIRECTORPELIField;
        
        private string gENEROPELIField;
        
        private FICHARENTA[] fICHARENTAField;
        
        /// <remarks/>
        public string PELIID {
            get {
                return this.pELIIDField;
            }
            set {
                this.pELIIDField = value;
            }
        }
        
        /// <remarks/>
        public string NOMBREPELI {
            get {
                return this.nOMBREPELIField;
            }
            set {
                this.nOMBREPELIField = value;
            }
        }
        
        /// <remarks/>
        public string DIRECTORPELI {
            get {
                return this.dIRECTORPELIField;
            }
            set {
                this.dIRECTORPELIField = value;
            }
        }
        
        /// <remarks/>
        public string GENEROPELI {
            get {
                return this.gENEROPELIField;
            }
            set {
                this.gENEROPELIField = value;
            }
        }
        
        /// <remarks/>
        public FICHARENTA[] FICHARENTA {
            get {
                return this.fICHARENTAField;
            }
            set {
                this.fICHARENTAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FICHARENTA {
        
        private string rENTIDField;
        
        private string pELIIDField;
        
        private string cLIIDField;
        
        private string fECHAREGRENTField;
        
        private string fECHADEVRENTField;
        
        private string fECHAENTRENTField;
        
        private CLIENTE cLIENTEField;
        
        private PELICULA pELICULAField;
        
        /// <remarks/>
        public string RENTID {
            get {
                return this.rENTIDField;
            }
            set {
                this.rENTIDField = value;
            }
        }
        
        /// <remarks/>
        public string PELIID {
            get {
                return this.pELIIDField;
            }
            set {
                this.pELIIDField = value;
            }
        }
        
        /// <remarks/>
        public string CLIID {
            get {
                return this.cLIIDField;
            }
            set {
                this.cLIIDField = value;
            }
        }
        
        /// <remarks/>
        public string FECHAREGRENT {
            get {
                return this.fECHAREGRENTField;
            }
            set {
                this.fECHAREGRENTField = value;
            }
        }
        
        /// <remarks/>
        public string FECHADEVRENT {
            get {
                return this.fECHADEVRENTField;
            }
            set {
                this.fECHADEVRENTField = value;
            }
        }
        
        /// <remarks/>
        public string FECHAENTRENT {
            get {
                return this.fECHAENTRENTField;
            }
            set {
                this.fECHAENTRENTField = value;
            }
        }
        
        /// <remarks/>
        public CLIENTE CLIENTE {
            get {
                return this.cLIENTEField;
            }
            set {
                this.cLIENTEField = value;
            }
        }
        
        /// <remarks/>
        public PELICULA PELICULA {
            get {
                return this.pELICULAField;
            }
            set {
                this.pELICULAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SeleccionarClienteCompletedEventHandler(object sender, SeleccionarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeleccionarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeleccionarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CLIENTE[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CLIENTE[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SeleccionarClientePorIDCompletedEventHandler(object sender, SeleccionarClientePorIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeleccionarClientePorIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeleccionarClientePorIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CLIENTE Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CLIENTE)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void InsertarClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ActualizarClienteCompletedEventHandler(object sender, ActualizarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EliminarClienteCompletedEventHandler(object sender, EliminarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SeleccionarClientesDefCompletedEventHandler(object sender, SeleccionarClientesDefCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeleccionarClientesDefCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeleccionarClientesDefCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CLIENTE[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CLIENTE[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591