//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FrontRentaPeliculas.SWPeliculas {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SWPeliculasSoap", Namespace="http://tempuri.org/")]
    public partial class SWPeliculas : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SeleccionarPeliculasOperationCompleted;
        
        private System.Threading.SendOrPostCallback SeleccionarPeliculaPorIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarPeliculaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarPeliculaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarPeliculaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SeleccionarPeliculasDefOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SWPeliculas() {
            this.Url = global::FrontRentaPeliculas.Properties.Settings.Default.FrontRentaPeliculas_SWPeliculas_SWPeliculas;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SeleccionarPeliculasCompletedEventHandler SeleccionarPeliculasCompleted;
        
        /// <remarks/>
        public event SeleccionarPeliculaPorIDCompletedEventHandler SeleccionarPeliculaPorIDCompleted;
        
        /// <remarks/>
        public event InsertarPeliculaCompletedEventHandler InsertarPeliculaCompleted;
        
        /// <remarks/>
        public event ActualizarPeliculaCompletedEventHandler ActualizarPeliculaCompleted;
        
        /// <remarks/>
        public event EliminarPeliculaCompletedEventHandler EliminarPeliculaCompleted;
        
        /// <remarks/>
        public event SeleccionarPeliculasDefCompletedEventHandler SeleccionarPeliculasDefCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeleccionarPeliculas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PELICULA[] SeleccionarPeliculas() {
            object[] results = this.Invoke("SeleccionarPeliculas", new object[0]);
            return ((PELICULA[])(results[0]));
        }
        
        /// <remarks/>
        public void SeleccionarPeliculasAsync() {
            this.SeleccionarPeliculasAsync(null);
        }
        
        /// <remarks/>
        public void SeleccionarPeliculasAsync(object userState) {
            if ((this.SeleccionarPeliculasOperationCompleted == null)) {
                this.SeleccionarPeliculasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeleccionarPeliculasOperationCompleted);
            }
            this.InvokeAsync("SeleccionarPeliculas", new object[0], this.SeleccionarPeliculasOperationCompleted, userState);
        }
        
        private void OnSeleccionarPeliculasOperationCompleted(object arg) {
            if ((this.SeleccionarPeliculasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeleccionarPeliculasCompleted(this, new SeleccionarPeliculasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeleccionarPeliculaPorID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PELICULA SeleccionarPeliculaPorID(string ID) {
            object[] results = this.Invoke("SeleccionarPeliculaPorID", new object[] {
                        ID});
            return ((PELICULA)(results[0]));
        }
        
        /// <remarks/>
        public void SeleccionarPeliculaPorIDAsync(string ID) {
            this.SeleccionarPeliculaPorIDAsync(ID, null);
        }
        
        /// <remarks/>
        public void SeleccionarPeliculaPorIDAsync(string ID, object userState) {
            if ((this.SeleccionarPeliculaPorIDOperationCompleted == null)) {
                this.SeleccionarPeliculaPorIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeleccionarPeliculaPorIDOperationCompleted);
            }
            this.InvokeAsync("SeleccionarPeliculaPorID", new object[] {
                        ID}, this.SeleccionarPeliculaPorIDOperationCompleted, userState);
        }
        
        private void OnSeleccionarPeliculaPorIDOperationCompleted(object arg) {
            if ((this.SeleccionarPeliculaPorIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeleccionarPeliculaPorIDCompleted(this, new SeleccionarPeliculaPorIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertarPelicula", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertarPelicula(PELICULA pel) {
            this.Invoke("InsertarPelicula", new object[] {
                        pel});
        }
        
        /// <remarks/>
        public void InsertarPeliculaAsync(PELICULA pel) {
            this.InsertarPeliculaAsync(pel, null);
        }
        
        /// <remarks/>
        public void InsertarPeliculaAsync(PELICULA pel, object userState) {
            if ((this.InsertarPeliculaOperationCompleted == null)) {
                this.InsertarPeliculaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarPeliculaOperationCompleted);
            }
            this.InvokeAsync("InsertarPelicula", new object[] {
                        pel}, this.InsertarPeliculaOperationCompleted, userState);
        }
        
        private void OnInsertarPeliculaOperationCompleted(object arg) {
            if ((this.InsertarPeliculaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarPeliculaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarPelicula", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ActualizarPelicula(PELICULA pel) {
            object[] results = this.Invoke("ActualizarPelicula", new object[] {
                        pel});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarPeliculaAsync(PELICULA pel) {
            this.ActualizarPeliculaAsync(pel, null);
        }
        
        /// <remarks/>
        public void ActualizarPeliculaAsync(PELICULA pel, object userState) {
            if ((this.ActualizarPeliculaOperationCompleted == null)) {
                this.ActualizarPeliculaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarPeliculaOperationCompleted);
            }
            this.InvokeAsync("ActualizarPelicula", new object[] {
                        pel}, this.ActualizarPeliculaOperationCompleted, userState);
        }
        
        private void OnActualizarPeliculaOperationCompleted(object arg) {
            if ((this.ActualizarPeliculaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarPeliculaCompleted(this, new ActualizarPeliculaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarPelicula", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarPelicula(PELICULA pel) {
            object[] results = this.Invoke("EliminarPelicula", new object[] {
                        pel});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarPeliculaAsync(PELICULA pel) {
            this.EliminarPeliculaAsync(pel, null);
        }
        
        /// <remarks/>
        public void EliminarPeliculaAsync(PELICULA pel, object userState) {
            if ((this.EliminarPeliculaOperationCompleted == null)) {
                this.EliminarPeliculaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarPeliculaOperationCompleted);
            }
            this.InvokeAsync("EliminarPelicula", new object[] {
                        pel}, this.EliminarPeliculaOperationCompleted, userState);
        }
        
        private void OnEliminarPeliculaOperationCompleted(object arg) {
            if ((this.EliminarPeliculaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarPeliculaCompleted(this, new EliminarPeliculaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeleccionarPeliculasDef", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PELICULA[] SeleccionarPeliculasDef(string ID) {
            object[] results = this.Invoke("SeleccionarPeliculasDef", new object[] {
                        ID});
            return ((PELICULA[])(results[0]));
        }
        
        /// <remarks/>
        public void SeleccionarPeliculasDefAsync(string ID) {
            this.SeleccionarPeliculasDefAsync(ID, null);
        }
        
        /// <remarks/>
        public void SeleccionarPeliculasDefAsync(string ID, object userState) {
            if ((this.SeleccionarPeliculasDefOperationCompleted == null)) {
                this.SeleccionarPeliculasDefOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeleccionarPeliculasDefOperationCompleted);
            }
            this.InvokeAsync("SeleccionarPeliculasDef", new object[] {
                        ID}, this.SeleccionarPeliculasDefOperationCompleted, userState);
        }
        
        private void OnSeleccionarPeliculasDefOperationCompleted(object arg) {
            if ((this.SeleccionarPeliculasDefCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeleccionarPeliculasDefCompleted(this, new SeleccionarPeliculasDefCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PELICULA {
        
        private string pELIIDField;
        
        private string nOMBREPELIField;
        
        private string dIRECTORPELIField;
        
        private string gENEROPELIField;
        
        private FICHARENTA[] fICHARENTAField;
        
        /// <remarks/>
        public string PELIID {
            get {
                return this.pELIIDField;
            }
            set {
                this.pELIIDField = value;
            }
        }
        
        /// <remarks/>
        public string NOMBREPELI {
            get {
                return this.nOMBREPELIField;
            }
            set {
                this.nOMBREPELIField = value;
            }
        }
        
        /// <remarks/>
        public string DIRECTORPELI {
            get {
                return this.dIRECTORPELIField;
            }
            set {
                this.dIRECTORPELIField = value;
            }
        }
        
        /// <remarks/>
        public string GENEROPELI {
            get {
                return this.gENEROPELIField;
            }
            set {
                this.gENEROPELIField = value;
            }
        }
        
        /// <remarks/>
        public FICHARENTA[] FICHARENTA {
            get {
                return this.fICHARENTAField;
            }
            set {
                this.fICHARENTAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FICHARENTA {
        
        private string rENTIDField;
        
        private string pELIIDField;
        
        private string cLIIDField;
        
        private string fECHAREGRENTField;
        
        private string fECHADEVRENTField;
        
        private string fECHAENTRENTField;
        
        private CLIENTE cLIENTEField;
        
        private PELICULA pELICULAField;
        
        /// <remarks/>
        public string RENTID {
            get {
                return this.rENTIDField;
            }
            set {
                this.rENTIDField = value;
            }
        }
        
        /// <remarks/>
        public string PELIID {
            get {
                return this.pELIIDField;
            }
            set {
                this.pELIIDField = value;
            }
        }
        
        /// <remarks/>
        public string CLIID {
            get {
                return this.cLIIDField;
            }
            set {
                this.cLIIDField = value;
            }
        }
        
        /// <remarks/>
        public string FECHAREGRENT {
            get {
                return this.fECHAREGRENTField;
            }
            set {
                this.fECHAREGRENTField = value;
            }
        }
        
        /// <remarks/>
        public string FECHADEVRENT {
            get {
                return this.fECHADEVRENTField;
            }
            set {
                this.fECHADEVRENTField = value;
            }
        }
        
        /// <remarks/>
        public string FECHAENTRENT {
            get {
                return this.fECHAENTRENTField;
            }
            set {
                this.fECHAENTRENTField = value;
            }
        }
        
        /// <remarks/>
        public CLIENTE CLIENTE {
            get {
                return this.cLIENTEField;
            }
            set {
                this.cLIENTEField = value;
            }
        }
        
        /// <remarks/>
        public PELICULA PELICULA {
            get {
                return this.pELICULAField;
            }
            set {
                this.pELICULAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CLIENTE {
        
        private string cLIIDField;
        
        private string mEMIDField;
        
        private string nOMBRECLIField;
        
        private string cEDULACLIField;
        
        private string eMAILCLIField;
        
        private MEMBRESIA mEMBRESIAField;
        
        private FICHARENTA[] fICHARENTAField;
        
        /// <remarks/>
        public string CLIID {
            get {
                return this.cLIIDField;
            }
            set {
                this.cLIIDField = value;
            }
        }
        
        /// <remarks/>
        public string MEMID {
            get {
                return this.mEMIDField;
            }
            set {
                this.mEMIDField = value;
            }
        }
        
        /// <remarks/>
        public string NOMBRECLI {
            get {
                return this.nOMBRECLIField;
            }
            set {
                this.nOMBRECLIField = value;
            }
        }
        
        /// <remarks/>
        public string CEDULACLI {
            get {
                return this.cEDULACLIField;
            }
            set {
                this.cEDULACLIField = value;
            }
        }
        
        /// <remarks/>
        public string EMAILCLI {
            get {
                return this.eMAILCLIField;
            }
            set {
                this.eMAILCLIField = value;
            }
        }
        
        /// <remarks/>
        public MEMBRESIA MEMBRESIA {
            get {
                return this.mEMBRESIAField;
            }
            set {
                this.mEMBRESIAField = value;
            }
        }
        
        /// <remarks/>
        public FICHARENTA[] FICHARENTA {
            get {
                return this.fICHARENTAField;
            }
            set {
                this.fICHARENTAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MEMBRESIA {
        
        private string mEMIDField;
        
        private string cLIIDField;
        
        private string fECHAREGMEMField;
        
        private string fECHAEXOMEMField;
        
        private CLIENTE cLIENTE1Field;
        
        /// <remarks/>
        public string MEMID {
            get {
                return this.mEMIDField;
            }
            set {
                this.mEMIDField = value;
            }
        }
        
        /// <remarks/>
        public string CLIID {
            get {
                return this.cLIIDField;
            }
            set {
                this.cLIIDField = value;
            }
        }
        
        /// <remarks/>
        public string FECHAREGMEM {
            get {
                return this.fECHAREGMEMField;
            }
            set {
                this.fECHAREGMEMField = value;
            }
        }
        
        /// <remarks/>
        public string FECHAEXOMEM {
            get {
                return this.fECHAEXOMEMField;
            }
            set {
                this.fECHAEXOMEMField = value;
            }
        }
        
        /// <remarks/>
        public CLIENTE CLIENTE1 {
            get {
                return this.cLIENTE1Field;
            }
            set {
                this.cLIENTE1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SeleccionarPeliculasCompletedEventHandler(object sender, SeleccionarPeliculasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeleccionarPeliculasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeleccionarPeliculasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PELICULA[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PELICULA[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SeleccionarPeliculaPorIDCompletedEventHandler(object sender, SeleccionarPeliculaPorIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeleccionarPeliculaPorIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeleccionarPeliculaPorIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PELICULA Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PELICULA)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void InsertarPeliculaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ActualizarPeliculaCompletedEventHandler(object sender, ActualizarPeliculaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarPeliculaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarPeliculaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EliminarPeliculaCompletedEventHandler(object sender, EliminarPeliculaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarPeliculaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarPeliculaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SeleccionarPeliculasDefCompletedEventHandler(object sender, SeleccionarPeliculasDefCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeleccionarPeliculasDefCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeleccionarPeliculasDefCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PELICULA[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PELICULA[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591