//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppOrdenesCompra
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenCompras
    {
        public string OrdID { get; set; }
        public string OrdArtID { get; set; }
        public string OrdProvID { get; set; }
    }
}
