//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto_CHEV
    {
        public int id { get; set; }
        public string Marca_Chevrolet { get; set; }
        public string Modelo_Chevrolet { get; set; }
        public string Cilindraje_Chevrolet { get; set; }
        public string Anio_Chevrolet { get; set; }
        public string Color_Chevrolet { get; set; }
        public string Tipo_Chevrolet { get; set; }
        public string Con_Chevrolet { get; set; }
        public string Fecha_Chevrolet { get; set; }
        public string img_Chevrolet { get; set; }
    }
}
